version: '3.5'

services:
  mrsm-compose:
    build:
      context: "./"
      dockerfile: "./docker/Dockerfile"

    entrypoint: ["/app/docker/sleep_forever.sh"]
    environment:

      MRSM_PLUGINS_DIR: |-
        ["/meerschaum/plugins", "/app/plugins"]

      MRSM_CONFIG: |-
        {
          "meerschaum": {
            "instance": "mongodb:local"
          }
        }

      MRSM_MONGODB_LOCAL: |-
        {
          "uri": "mongodb://localhost:27017",
          "database": "meerschaum"
        }

    network_mode: "host"
    volumes:
      - "./:/app"
    init: true
    tty: true
    stdin_open: true
    user: "meerschaum"

  mongodb:
    image: "mongo"
    network_mode: "host"
