project_name: "mongodb-connector"
root_dir: "/meerschaum"

plugins_dir:
  - "/meerschaum/plugins"
  - "/app/plugins"

plugins:
  - "stress"

sync:
  pipes:
    - connector: "plugin:stress"
      metric: "test"
      parameters:
        fetch:
          rows: 1
          ids: 1

    - connector: "mongodb:local"
      metric: "test"
      parameters:
        fetch:
          collection: "plugin_stress_test"
          query: {}
          projection: {}
      columns:
        datetime: "datetime"
        id: "id"

config:
  meerschaum:
    instance: "mongodb:local"
    connectors:
      mongodb:
        local: MRSM{meerschaum:connectors:mongodb:local}

environment: {}
