### This is for re-using the existing Docker root.
### Omit to create a local dir (defaults to ./root).
root_dir: "/meerschaum"

plugins_dir:
  - "/meerschaum/plugins"
  - "/app/plugins"

plugins:
  - "stress"

### All pipes are tagged with the project name
### (defaults to directory name).
project_name: "mongodb-connector"

### 1. Module-level `fetch()` (plugin:example)
### 2. Custom connector `fetch()` (example:secret)
sync:
  pipes:
    - connector: "plugin:stress"
      metric: "test"
      parameters:
        fetch:
          rows: 1
          ids: 1

### Define the MRSM_CONFIG for this isolated project.
config:
  meerschaum:
    instance: "mongodb:local"
    connectors:
      mongodb:
        local: MRSM{meerschaum:connectors:mongodb:local}

### Other environment variables to include (e.g. AWS creds).
environment: {}
